name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bump up the version
      run: |
        python3 -m pip install python-semantic-release
        semantic-release publish
